### PR TITLE
first draft for data-fetch

### PR DESCRIPTION
**Pull request by pm-moyanor**
first data-fetch logic, I created a new component to be separated from the main components, we can delete it later if needed. details need to be adjusted, like replacing the endpoint to search actual "ingredients"

### CODE REVIEW

**Comment by chef-louis** [comment]
@pm-moyanor Nice job with the data fetch logic :)

One suggestion -- I have 2 components that will fetch from the API (for building individual Cards and also Card Details) so turning the Fetch into a custom hook could be useful, but also open to other avenues you and Pavu come up with.

**Comment by pm-moyanor** [comment]
Thanks, yeah I also thought about using useContext, but your option seems like a great solution

**Comment by chef-louis** [comment]
@pm-moyanor Great point, I think useContext will fit the bill nicely for this project & API.

**Comment by pm-moyanor** [comment]
Maybe we can keep the custom hook as an option after MVP, if we add filters, for example, we can refactor if needed

**Pull request merged**
